### PR TITLE
Update hook.c

### PR DESCRIPTION
**Pull request by Symbai**
Fix typo

//edit: And thank you for creating the multi hook version <3

### CODE REVIEW

**Comment by m417z** [comment]
I didn't document the `hookIdent` parameter, and it's a fairly new addition that I'm using in a new project which is still a work in progress. Yet, I don't believe that your change is correct. Can you explain your motivation behind it?

**Comment by Symbai** [comment]
https://github.com/m417z/minhook/blob/cc777e744b3bf664ad7a1b0fa1e705569d7131df/src/hook.c#L470-L471

Passing `false` will `bAllIdents` to `false`. If `bAllIdents` is `false` it will take `hookIdent` instead. However we want to disable all hooks. I've tested it myself. Calling `MH_RemoveHookEx` with `MH_ALL_HOOKS` will currently disable no hook at all. My commit fixes it.

**Comment by m417z** [comment]
That's the intended behavior. For all APIs, including `MH_RemoveHookEx`, `MH_ALL_HOOKS` is limited to all hooks of a specific ident. There's no way to truly refer to all hooks of all idents.

How are you using different idents? If you're not using them at all (i.e. not calling the Ex functions), idents are always zero, and `MH_ALL_HOOKS` truly refers to all hooks, so the change is backwards compatible. My use case is having an ident per module which is loaded in the process, and each module should have no reason fiddling with hooks of other modules.

**Comment by Symbai** [comment]
I am using the Ex function s and unique identifier. But when shutting my hook library down I want to unhook ALL hooks at once. My commit does this. If you believe this is not indented you can close the pull request. For me it was exactly what I wanted and there was no other way as of now. At least not in a single line.

**Comment by m417z** [comment]
Unloading the library with `MH_Uninitialize` disables and removes all created hooks for you, if that's what you're after.

**Pull request closed without merging**
